# general
gpu_id: 0
use_gpu: True
seed: 2120
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: True
save_dataloaders: True

# dataset
load_col:
    inter: [user_id, item_id, rating, timestamp]
MAX_ITEM_LIST_LENGTH: 50
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

# Filtering
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# Model
n_layers: 4
n_heads: 8
hidden_size: 256
inner_size: 256
hidden_dropout_prob: 0.3
attn_dropout_prob: 0.3
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
pooling_mode: 'sum' # sum, mean, max
loss_type: 'CE'



# patch
patch_len: 2
stride: 1
patch_fusion: 'last'    # ['linear', 'last', 'mean', 'sum']
padding_patch: 'repeat' # ['end', 'repeat']
patch_lambda: 0.5       # [0.1, 0.3, 0.5, 0.7, 1.0]
sim: 'dot'              # choose from {dot, cos}
dropseq: True           # (bool) Whether to use the dropout layer in the sequence.
contrast: 'us' 
lmd: 0.1                # (float) The weight of unsupervised normalized CE loss.
tau: 1                  # (float) The temperature parameter.


# training settings
epochs: 300
train_batch_size: 1024 # 1024
learner: adam
learning_rate: 0.0001
eval_step: 2
stopping_step: 7
clip_grad_norm: ~
weight_decay: 0.0
neg_sampling: 

# evaluation settings
eval_args:
  split: { 'RS':[0.8,0.1,0.1] } # split: { 'LS': 'valid_and_test' }
  group_by: user
  order: TO
  mode: full

# disable negative sampling
train_neg_sample_args: ~

repeatable: True
metrics: ["Recall","NDCG", "MRR", "HIT", "MAP"]
topk: [5,10,20]
valid_metric: Recall@20
valid_metric_bigger: True
eval_batch_size: 4096
loss_decimal_place: 4
metric_decimal_place: 4